// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/group/enrollment/delete_group_invitation_request.proto

package im.micro.access.pojo.request.group.enrollment;

public interface DeleteGroupInvitationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.DeleteGroupInvitationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 invitation_id = 1;</code>
   * @return The invitationId.
   */
  long getInvitationId();
}
