// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/query_users_ids_nearby_request.proto

package im.micro.access.pojo.request.user;

public final class QueryUsersIdsNearbyRequestOuterClass {
  private QueryUsersIdsNearbyRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_micro_proto_QueryUsersIdsNearbyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_micro_proto_QueryUsersIdsNearbyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1request/user/query_users_ids_nearby_re" +
      "quest.proto\022\016im.micro.proto\032\036google/prot" +
      "obuf/wrappers.proto\"\240\001\n\032QueryUsersIdsNea" +
      "rbyRequest\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitud" +
      "e\030\002 \001(\002\022-\n\010distance\030\003 \001(\0132\033.google.proto" +
      "buf.FloatValue\022.\n\tmaxNumber\030\004 \001(\0132\033.goog" +
      "le.protobuf.Int32ValueB%\n!im.micro.acces" +
      "s.pojo.request.userP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_micro_proto_QueryUsersIdsNearbyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_micro_proto_QueryUsersIdsNearbyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_micro_proto_QueryUsersIdsNearbyRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Distance", "MaxNumber", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
