// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/query_user_group_invitations_request.proto

package im.micro.access.pojo.request.user;

public final class QueryUserGroupInvitationsRequestOuterClass {
  private QueryUserGroupInvitationsRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_micro_proto_QueryUserGroupInvitationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_micro_proto_QueryUserGroupInvitationsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7request/user/query_user_group_invitati" +
      "ons_request.proto\022\016im.micro.proto\032\036googl" +
      "e/protobuf/wrappers.proto\"Z\n QueryUserGr" +
      "oupInvitationsRequest\0226\n\021last_updated_da" +
      "te\030\001 \001(\0132\033.google.protobuf.Int64ValueB%\n" +
      "!im.micro.access.pojo.request.userP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_micro_proto_QueryUserGroupInvitationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_micro_proto_QueryUserGroupInvitationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_micro_proto_QueryUserGroupInvitationsRequest_descriptor,
        new java.lang.String[] { "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
