// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/update_user_online_status_request.proto

package im.micro.access.pojo.request.user;

public interface UpdateUserOnlineStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.UpdateUserOnlineStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.im.micro.proto.UserStatus user_status = 1;</code>
   * @return The enum numeric value on the wire for userStatus.
   */
  int getUserStatusValue();
  /**
   * <code>.im.micro.proto.UserStatus user_status = 1;</code>
   * @return The userStatus.
   */
  im.micro.access.constant.UserStatus getUserStatus();
}
