// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/message_statuses.proto

package im.micro.access.pojo.bo.message;

public final class MessageStatusesOuterClass {
  private MessageStatusesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_MessageStatuses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_MessageStatuses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$model/message/message_statuses.proto\022\016" +
      "im.turms.proto\032\"model/message/message_st" +
      "atus.proto\"J\n\017MessageStatuses\0227\n\020message" +
      "_statuses\030\001 \003(\0132\035.im.turms.proto.Message" +
      "StatusB#\n\037im.micro.access.pojo.bo.messag" +
      "eP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          im.micro.access.pojo.bo.message.MessageStatusOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_MessageStatuses_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_MessageStatuses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_MessageStatuses_descriptor,
        new java.lang.String[] { "MessageStatuses", });
    im.micro.access.pojo.bo.message.MessageStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
