// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/message_statuses.proto

package im.micro.access.pojo.bo.message;

public interface MessageStatusesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.MessageStatuses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  java.util.List<im.micro.access.pojo.bo.message.MessageStatus> 
      getMessageStatusesList();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  im.micro.access.pojo.bo.message.MessageStatus getMessageStatuses(int index);
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  int getMessageStatusesCount();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  java.util.List<? extends im.micro.access.pojo.bo.message.MessageStatusOrBuilder> 
      getMessageStatusesOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  im.micro.access.pojo.bo.message.MessageStatusOrBuilder getMessageStatusesOrBuilder(
      int index);
}
