// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/messages_with_total_list.proto

package im.micro.access.pojo.bo.message;

public interface MessagesWithTotalListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.MessagesWithTotalList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.micro.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  java.util.List<im.micro.access.pojo.bo.message.MessagesWithTotal> 
      getMessagesWithTotalListList();
  /**
   * <code>repeated .im.micro.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  im.micro.access.pojo.bo.message.MessagesWithTotal getMessagesWithTotalList(int index);
  /**
   * <code>repeated .im.micro.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  int getMessagesWithTotalListCount();
  /**
   * <code>repeated .im.micro.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  java.util.List<? extends im.micro.access.pojo.bo.message.MessagesWithTotalOrBuilder> 
      getMessagesWithTotalListOrBuilderList();
  /**
   * <code>repeated .im.micro.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  im.micro.access.pojo.bo.message.MessagesWithTotalOrBuilder getMessagesWithTotalListOrBuilder(
      int index);
}
