// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/message_status.proto

package im.micro.access.pojo.bo.message;

/**
 * Protobuf type {@code im.turms.proto.MessageStatus}
 */
public  final class MessageStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.MessageStatus)
    MessageStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageStatus.newBuilder() to construct.
  private MessageStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageStatus() {
    deliveryStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (messageId_ != null) {
              subBuilder = messageId_.toBuilder();
            }
            messageId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageId_);
              messageId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (toUserId_ != null) {
              subBuilder = toUserId_.toBuilder();
            }
            toUserId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(toUserId_);
              toUserId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            deliveryStatus_ = rawValue;
            break;
          }
          case 34: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (receptionDate_ != null) {
              subBuilder = receptionDate_.toBuilder();
            }
            receptionDate_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(receptionDate_);
              receptionDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (readDate_ != null) {
              subBuilder = readDate_.toBuilder();
            }
            readDate_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(readDate_);
              readDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (recallDate_ != null) {
              subBuilder = recallDate_.toBuilder();
            }
            recallDate_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(recallDate_);
              recallDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.micro.access.pojo.bo.message.MessageStatusOuterClass.internal_static_im_turms_proto_MessageStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.micro.access.pojo.bo.message.MessageStatusOuterClass.internal_static_im_turms_proto_MessageStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.micro.access.pojo.bo.message.MessageStatus.class, im.micro.access.pojo.bo.message.MessageStatus.Builder.class);
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value messageId_;
  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   * @return Whether the messageId field is set.
   */
  public boolean hasMessageId() {
    return messageId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   * @return The messageId.
   */
  public com.google.protobuf.Int64Value getMessageId() {
    return messageId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : messageId_;
  }
  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getMessageIdOrBuilder() {
    return getMessageId();
  }

  public static final int TO_USER_ID_FIELD_NUMBER = 2;
  private com.google.protobuf.Int64Value toUserId_;
  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   * @return Whether the toUserId field is set.
   */
  public boolean hasToUserId() {
    return toUserId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   * @return The toUserId.
   */
  public com.google.protobuf.Int64Value getToUserId() {
    return toUserId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : toUserId_;
  }
  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getToUserIdOrBuilder() {
    return getToUserId();
  }

  public static final int DELIVERY_STATUS_FIELD_NUMBER = 3;
  private int deliveryStatus_;
  /**
   * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
   * @return The enum numeric value on the wire for deliveryStatus.
   */
  public int getDeliveryStatusValue() {
    return deliveryStatus_;
  }
  /**
   * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
   * @return The deliveryStatus.
   */
  public im.micro.access.constant.MessageDeliveryStatus getDeliveryStatus() {
    @SuppressWarnings("deprecation")
    im.micro.access.constant.MessageDeliveryStatus result = im.micro.access.constant.MessageDeliveryStatus.valueOf(deliveryStatus_);
    return result == null ? im.micro.access.constant.MessageDeliveryStatus.UNRECOGNIZED : result;
  }

  public static final int RECEPTION_DATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Int64Value receptionDate_;
  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   * @return Whether the receptionDate field is set.
   */
  public boolean hasReceptionDate() {
    return receptionDate_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   * @return The receptionDate.
   */
  public com.google.protobuf.Int64Value getReceptionDate() {
    return receptionDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : receptionDate_;
  }
  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getReceptionDateOrBuilder() {
    return getReceptionDate();
  }

  public static final int READ_DATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Int64Value readDate_;
  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   * @return Whether the readDate field is set.
   */
  public boolean hasReadDate() {
    return readDate_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   * @return The readDate.
   */
  public com.google.protobuf.Int64Value getReadDate() {
    return readDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : readDate_;
  }
  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getReadDateOrBuilder() {
    return getReadDate();
  }

  public static final int RECALL_DATE_FIELD_NUMBER = 6;
  private com.google.protobuf.Int64Value recallDate_;
  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   * @return Whether the recallDate field is set.
   */
  public boolean hasRecallDate() {
    return recallDate_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   * @return The recallDate.
   */
  public com.google.protobuf.Int64Value getRecallDate() {
    return recallDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : recallDate_;
  }
  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getRecallDateOrBuilder() {
    return getRecallDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageId_ != null) {
      output.writeMessage(1, getMessageId());
    }
    if (toUserId_ != null) {
      output.writeMessage(2, getToUserId());
    }
    if (deliveryStatus_ != im.micro.access.constant.MessageDeliveryStatus.READY.getNumber()) {
      output.writeEnum(3, deliveryStatus_);
    }
    if (receptionDate_ != null) {
      output.writeMessage(4, getReceptionDate());
    }
    if (readDate_ != null) {
      output.writeMessage(5, getReadDate());
    }
    if (recallDate_ != null) {
      output.writeMessage(6, getRecallDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessageId());
    }
    if (toUserId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getToUserId());
    }
    if (deliveryStatus_ != im.micro.access.constant.MessageDeliveryStatus.READY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, deliveryStatus_);
    }
    if (receptionDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getReceptionDate());
    }
    if (readDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getReadDate());
    }
    if (recallDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRecallDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.micro.access.pojo.bo.message.MessageStatus)) {
      return super.equals(obj);
    }
    im.micro.access.pojo.bo.message.MessageStatus other = (im.micro.access.pojo.bo.message.MessageStatus) obj;

    if (hasMessageId() != other.hasMessageId()) return false;
    if (hasMessageId()) {
      if (!getMessageId()
          .equals(other.getMessageId())) return false;
    }
    if (hasToUserId() != other.hasToUserId()) return false;
    if (hasToUserId()) {
      if (!getToUserId()
          .equals(other.getToUserId())) return false;
    }
    if (deliveryStatus_ != other.deliveryStatus_) return false;
    if (hasReceptionDate() != other.hasReceptionDate()) return false;
    if (hasReceptionDate()) {
      if (!getReceptionDate()
          .equals(other.getReceptionDate())) return false;
    }
    if (hasReadDate() != other.hasReadDate()) return false;
    if (hasReadDate()) {
      if (!getReadDate()
          .equals(other.getReadDate())) return false;
    }
    if (hasRecallDate() != other.hasRecallDate()) return false;
    if (hasRecallDate()) {
      if (!getRecallDate()
          .equals(other.getRecallDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessageId()) {
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
    }
    if (hasToUserId()) {
      hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
    }
    hash = (37 * hash) + DELIVERY_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + deliveryStatus_;
    if (hasReceptionDate()) {
      hash = (37 * hash) + RECEPTION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getReceptionDate().hashCode();
    }
    if (hasReadDate()) {
      hash = (37 * hash) + READ_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getReadDate().hashCode();
    }
    if (hasRecallDate()) {
      hash = (37 * hash) + RECALL_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getRecallDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.bo.message.MessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.micro.access.pojo.bo.message.MessageStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.MessageStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.MessageStatus)
      im.micro.access.pojo.bo.message.MessageStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.micro.access.pojo.bo.message.MessageStatusOuterClass.internal_static_im_turms_proto_MessageStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.micro.access.pojo.bo.message.MessageStatusOuterClass.internal_static_im_turms_proto_MessageStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.micro.access.pojo.bo.message.MessageStatus.class, im.micro.access.pojo.bo.message.MessageStatus.Builder.class);
    }

    // Construct using im.micro.access.pojo.bo.message.MessageStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageIdBuilder_ == null) {
        messageId_ = null;
      } else {
        messageId_ = null;
        messageIdBuilder_ = null;
      }
      if (toUserIdBuilder_ == null) {
        toUserId_ = null;
      } else {
        toUserId_ = null;
        toUserIdBuilder_ = null;
      }
      deliveryStatus_ = 0;

      if (receptionDateBuilder_ == null) {
        receptionDate_ = null;
      } else {
        receptionDate_ = null;
        receptionDateBuilder_ = null;
      }
      if (readDateBuilder_ == null) {
        readDate_ = null;
      } else {
        readDate_ = null;
        readDateBuilder_ = null;
      }
      if (recallDateBuilder_ == null) {
        recallDate_ = null;
      } else {
        recallDate_ = null;
        recallDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.micro.access.pojo.bo.message.MessageStatusOuterClass.internal_static_im_turms_proto_MessageStatus_descriptor;
    }

    @java.lang.Override
    public im.micro.access.pojo.bo.message.MessageStatus getDefaultInstanceForType() {
      return im.micro.access.pojo.bo.message.MessageStatus.getDefaultInstance();
    }

    @java.lang.Override
    public im.micro.access.pojo.bo.message.MessageStatus build() {
      im.micro.access.pojo.bo.message.MessageStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.micro.access.pojo.bo.message.MessageStatus buildPartial() {
      im.micro.access.pojo.bo.message.MessageStatus result = new im.micro.access.pojo.bo.message.MessageStatus(this);
      if (messageIdBuilder_ == null) {
        result.messageId_ = messageId_;
      } else {
        result.messageId_ = messageIdBuilder_.build();
      }
      if (toUserIdBuilder_ == null) {
        result.toUserId_ = toUserId_;
      } else {
        result.toUserId_ = toUserIdBuilder_.build();
      }
      result.deliveryStatus_ = deliveryStatus_;
      if (receptionDateBuilder_ == null) {
        result.receptionDate_ = receptionDate_;
      } else {
        result.receptionDate_ = receptionDateBuilder_.build();
      }
      if (readDateBuilder_ == null) {
        result.readDate_ = readDate_;
      } else {
        result.readDate_ = readDateBuilder_.build();
      }
      if (recallDateBuilder_ == null) {
        result.recallDate_ = recallDate_;
      } else {
        result.recallDate_ = recallDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.micro.access.pojo.bo.message.MessageStatus) {
        return mergeFrom((im.micro.access.pojo.bo.message.MessageStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.micro.access.pojo.bo.message.MessageStatus other) {
      if (other == im.micro.access.pojo.bo.message.MessageStatus.getDefaultInstance()) return this;
      if (other.hasMessageId()) {
        mergeMessageId(other.getMessageId());
      }
      if (other.hasToUserId()) {
        mergeToUserId(other.getToUserId());
      }
      if (other.deliveryStatus_ != 0) {
        setDeliveryStatusValue(other.getDeliveryStatusValue());
      }
      if (other.hasReceptionDate()) {
        mergeReceptionDate(other.getReceptionDate());
      }
      if (other.hasReadDate()) {
        mergeReadDate(other.getReadDate());
      }
      if (other.hasRecallDate()) {
        mergeRecallDate(other.getRecallDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.micro.access.pojo.bo.message.MessageStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.micro.access.pojo.bo.message.MessageStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value messageId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> messageIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     * @return Whether the messageId field is set.
     */
    public boolean hasMessageId() {
      return messageIdBuilder_ != null || messageId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     * @return The messageId.
     */
    public com.google.protobuf.Int64Value getMessageId() {
      if (messageIdBuilder_ == null) {
        return messageId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : messageId_;
      } else {
        return messageIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public Builder setMessageId(com.google.protobuf.Int64Value value) {
      if (messageIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageId_ = value;
        onChanged();
      } else {
        messageIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public Builder setMessageId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (messageIdBuilder_ == null) {
        messageId_ = builderForValue.build();
        onChanged();
      } else {
        messageIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public Builder mergeMessageId(com.google.protobuf.Int64Value value) {
      if (messageIdBuilder_ == null) {
        if (messageId_ != null) {
          messageId_ =
            com.google.protobuf.Int64Value.newBuilder(messageId_).mergeFrom(value).buildPartial();
        } else {
          messageId_ = value;
        }
        onChanged();
      } else {
        messageIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public Builder clearMessageId() {
      if (messageIdBuilder_ == null) {
        messageId_ = null;
        onChanged();
      } else {
        messageId_ = null;
        messageIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getMessageIdBuilder() {
      
      onChanged();
      return getMessageIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getMessageIdOrBuilder() {
      if (messageIdBuilder_ != null) {
        return messageIdBuilder_.getMessageOrBuilder();
      } else {
        return messageId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : messageId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value message_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getMessageIdFieldBuilder() {
      if (messageIdBuilder_ == null) {
        messageIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getMessageId(),
                getParentForChildren(),
                isClean());
        messageId_ = null;
      }
      return messageIdBuilder_;
    }

    private com.google.protobuf.Int64Value toUserId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> toUserIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     * @return Whether the toUserId field is set.
     */
    public boolean hasToUserId() {
      return toUserIdBuilder_ != null || toUserId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     * @return The toUserId.
     */
    public com.google.protobuf.Int64Value getToUserId() {
      if (toUserIdBuilder_ == null) {
        return toUserId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : toUserId_;
      } else {
        return toUserIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public Builder setToUserId(com.google.protobuf.Int64Value value) {
      if (toUserIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toUserId_ = value;
        onChanged();
      } else {
        toUserIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public Builder setToUserId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (toUserIdBuilder_ == null) {
        toUserId_ = builderForValue.build();
        onChanged();
      } else {
        toUserIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public Builder mergeToUserId(com.google.protobuf.Int64Value value) {
      if (toUserIdBuilder_ == null) {
        if (toUserId_ != null) {
          toUserId_ =
            com.google.protobuf.Int64Value.newBuilder(toUserId_).mergeFrom(value).buildPartial();
        } else {
          toUserId_ = value;
        }
        onChanged();
      } else {
        toUserIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public Builder clearToUserId() {
      if (toUserIdBuilder_ == null) {
        toUserId_ = null;
        onChanged();
      } else {
        toUserId_ = null;
        toUserIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public com.google.protobuf.Int64Value.Builder getToUserIdBuilder() {
      
      onChanged();
      return getToUserIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getToUserIdOrBuilder() {
      if (toUserIdBuilder_ != null) {
        return toUserIdBuilder_.getMessageOrBuilder();
      } else {
        return toUserId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : toUserId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getToUserIdFieldBuilder() {
      if (toUserIdBuilder_ == null) {
        toUserIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getToUserId(),
                getParentForChildren(),
                isClean());
        toUserId_ = null;
      }
      return toUserIdBuilder_;
    }

    private int deliveryStatus_ = 0;
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
     * @return The enum numeric value on the wire for deliveryStatus.
     */
    public int getDeliveryStatusValue() {
      return deliveryStatus_;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
     * @param value The enum numeric value on the wire for deliveryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryStatusValue(int value) {
      deliveryStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
     * @return The deliveryStatus.
     */
    public im.micro.access.constant.MessageDeliveryStatus getDeliveryStatus() {
      @SuppressWarnings("deprecation")
      im.micro.access.constant.MessageDeliveryStatus result = im.micro.access.constant.MessageDeliveryStatus.valueOf(deliveryStatus_);
      return result == null ? im.micro.access.constant.MessageDeliveryStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
     * @param value The deliveryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryStatus(im.micro.access.constant.MessageDeliveryStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      deliveryStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryStatus() {
      
      deliveryStatus_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value receptionDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> receptionDateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     * @return Whether the receptionDate field is set.
     */
    public boolean hasReceptionDate() {
      return receptionDateBuilder_ != null || receptionDate_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     * @return The receptionDate.
     */
    public com.google.protobuf.Int64Value getReceptionDate() {
      if (receptionDateBuilder_ == null) {
        return receptionDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : receptionDate_;
      } else {
        return receptionDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public Builder setReceptionDate(com.google.protobuf.Int64Value value) {
      if (receptionDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receptionDate_ = value;
        onChanged();
      } else {
        receptionDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public Builder setReceptionDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (receptionDateBuilder_ == null) {
        receptionDate_ = builderForValue.build();
        onChanged();
      } else {
        receptionDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public Builder mergeReceptionDate(com.google.protobuf.Int64Value value) {
      if (receptionDateBuilder_ == null) {
        if (receptionDate_ != null) {
          receptionDate_ =
            com.google.protobuf.Int64Value.newBuilder(receptionDate_).mergeFrom(value).buildPartial();
        } else {
          receptionDate_ = value;
        }
        onChanged();
      } else {
        receptionDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public Builder clearReceptionDate() {
      if (receptionDateBuilder_ == null) {
        receptionDate_ = null;
        onChanged();
      } else {
        receptionDate_ = null;
        receptionDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public com.google.protobuf.Int64Value.Builder getReceptionDateBuilder() {
      
      onChanged();
      return getReceptionDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getReceptionDateOrBuilder() {
      if (receptionDateBuilder_ != null) {
        return receptionDateBuilder_.getMessageOrBuilder();
      } else {
        return receptionDate_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : receptionDate_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value reception_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getReceptionDateFieldBuilder() {
      if (receptionDateBuilder_ == null) {
        receptionDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getReceptionDate(),
                getParentForChildren(),
                isClean());
        receptionDate_ = null;
      }
      return receptionDateBuilder_;
    }

    private com.google.protobuf.Int64Value readDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> readDateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     * @return Whether the readDate field is set.
     */
    public boolean hasReadDate() {
      return readDateBuilder_ != null || readDate_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     * @return The readDate.
     */
    public com.google.protobuf.Int64Value getReadDate() {
      if (readDateBuilder_ == null) {
        return readDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : readDate_;
      } else {
        return readDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public Builder setReadDate(com.google.protobuf.Int64Value value) {
      if (readDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        readDate_ = value;
        onChanged();
      } else {
        readDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public Builder setReadDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (readDateBuilder_ == null) {
        readDate_ = builderForValue.build();
        onChanged();
      } else {
        readDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public Builder mergeReadDate(com.google.protobuf.Int64Value value) {
      if (readDateBuilder_ == null) {
        if (readDate_ != null) {
          readDate_ =
            com.google.protobuf.Int64Value.newBuilder(readDate_).mergeFrom(value).buildPartial();
        } else {
          readDate_ = value;
        }
        onChanged();
      } else {
        readDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public Builder clearReadDate() {
      if (readDateBuilder_ == null) {
        readDate_ = null;
        onChanged();
      } else {
        readDate_ = null;
        readDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public com.google.protobuf.Int64Value.Builder getReadDateBuilder() {
      
      onChanged();
      return getReadDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getReadDateOrBuilder() {
      if (readDateBuilder_ != null) {
        return readDateBuilder_.getMessageOrBuilder();
      } else {
        return readDate_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : readDate_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value read_date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getReadDateFieldBuilder() {
      if (readDateBuilder_ == null) {
        readDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getReadDate(),
                getParentForChildren(),
                isClean());
        readDate_ = null;
      }
      return readDateBuilder_;
    }

    private com.google.protobuf.Int64Value recallDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> recallDateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     * @return Whether the recallDate field is set.
     */
    public boolean hasRecallDate() {
      return recallDateBuilder_ != null || recallDate_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     * @return The recallDate.
     */
    public com.google.protobuf.Int64Value getRecallDate() {
      if (recallDateBuilder_ == null) {
        return recallDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : recallDate_;
      } else {
        return recallDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public Builder setRecallDate(com.google.protobuf.Int64Value value) {
      if (recallDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recallDate_ = value;
        onChanged();
      } else {
        recallDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public Builder setRecallDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (recallDateBuilder_ == null) {
        recallDate_ = builderForValue.build();
        onChanged();
      } else {
        recallDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public Builder mergeRecallDate(com.google.protobuf.Int64Value value) {
      if (recallDateBuilder_ == null) {
        if (recallDate_ != null) {
          recallDate_ =
            com.google.protobuf.Int64Value.newBuilder(recallDate_).mergeFrom(value).buildPartial();
        } else {
          recallDate_ = value;
        }
        onChanged();
      } else {
        recallDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public Builder clearRecallDate() {
      if (recallDateBuilder_ == null) {
        recallDate_ = null;
        onChanged();
      } else {
        recallDate_ = null;
        recallDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public com.google.protobuf.Int64Value.Builder getRecallDateBuilder() {
      
      onChanged();
      return getRecallDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getRecallDateOrBuilder() {
      if (recallDateBuilder_ != null) {
        return recallDateBuilder_.getMessageOrBuilder();
      } else {
        return recallDate_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : recallDate_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value recall_date = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getRecallDateFieldBuilder() {
      if (recallDateBuilder_ == null) {
        recallDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getRecallDate(),
                getParentForChildren(),
                isClean());
        recallDate_ = null;
      }
      return recallDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.MessageStatus)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.MessageStatus)
  private static final im.micro.access.pojo.bo.message.MessageStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.micro.access.pojo.bo.message.MessageStatus();
  }

  public static im.micro.access.pojo.bo.message.MessageStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageStatus>
      PARSER = new com.google.protobuf.AbstractParser<MessageStatus>() {
    @java.lang.Override
    public MessageStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.micro.access.pojo.bo.message.MessageStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

