// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/message_status.proto

package im.micro.access.pojo.bo.message;

public interface MessageStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.MessageStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   * @return Whether the messageId field is set.
   */
  boolean hasMessageId();
  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   * @return The messageId.
   */
  com.google.protobuf.Int64Value getMessageId();
  /**
   * <code>.google.protobuf.Int64Value message_id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getMessageIdOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   * @return Whether the toUserId field is set.
   */
  boolean hasToUserId();
  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   * @return The toUserId.
   */
  com.google.protobuf.Int64Value getToUserId();
  /**
   * <code>.google.protobuf.Int64Value to_user_id = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getToUserIdOrBuilder();

  /**
   * <code>.im.micro.proto.MessageDeliveryStatus delivery_status = 3;</code>
   * @return The enum numeric value on the wire for deliveryStatus.
   */
  int getDeliveryStatusValue();
  /**
   * <code>.im.micro.proto.MessageDeliveryStatus delivery_status = 3;</code>
   * @return The deliveryStatus.
   */
  im.micro.access.constant.MessageDeliveryStatus getDeliveryStatus();

  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   * @return Whether the receptionDate field is set.
   */
  boolean hasReceptionDate();
  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   * @return The receptionDate.
   */
  com.google.protobuf.Int64Value getReceptionDate();
  /**
   * <code>.google.protobuf.Int64Value reception_date = 4;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getReceptionDateOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   * @return Whether the readDate field is set.
   */
  boolean hasReadDate();
  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   * @return The readDate.
   */
  com.google.protobuf.Int64Value getReadDate();
  /**
   * <code>.google.protobuf.Int64Value read_date = 5;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getReadDateOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   * @return Whether the recallDate field is set.
   */
  boolean hasRecallDate();
  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   * @return The recallDate.
   */
  com.google.protobuf.Int64Value getRecallDate();
  /**
   * <code>.google.protobuf.Int64Value recall_date = 6;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getRecallDateOrBuilder();
}
