// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification/micro_notification.proto

package im.micro.access.pojo.notification;

public interface MicroNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.MicroNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   * @return Whether the requestId field is set.
   */
  boolean hasRequestId();
  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   * @return The requestId.
   */
  com.google.protobuf.Int64Value getRequestId();
  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getRequestIdOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value code = 2;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>.google.protobuf.Int32Value code = 2;</code>
   * @return The code.
   */
  com.google.protobuf.Int32Value getCode();
  /**
   * <code>.google.protobuf.Int32Value code = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getCodeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   * @return The reason.
   */
  com.google.protobuf.StringValue getReason();
  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getReasonOrBuilder();

  /**
   * <code>.im.micro.proto.MicroNotification.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.im.micro.proto.MicroNotification.Data data = 4;</code>
   * @return The data.
   */
  im.micro.access.pojo.notification.MicroNotification.Data getData();
  /**
   * <code>.im.micro.proto.MicroNotification.Data data = 4;</code>
   */
  im.micro.access.pojo.notification.MicroNotification.DataOrBuilder getDataOrBuilder();

  /**
   * <code>.im.micro.proto.MicroRequest relayed_request = 5;</code>
   * @return Whether the relayedRequest field is set.
   */
  boolean hasRelayedRequest();
  /**
   * <code>.im.micro.proto.MicroRequest relayed_request = 5;</code>
   * @return The relayedRequest.
   */
  im.micro.access.pojo.request.MicroRequest getRelayedRequest();
  /**
   * <code>.im.micro.proto.MicroRequest relayed_request = 5;</code>
   */
  im.micro.access.pojo.request.MicroRequestOrBuilder getRelayedRequestOrBuilder();

  /**
   * <pre>
   * requester_id only exists when a requester triggers a notification to its recipients
   * Note: Do not move requester_id to microRequest because it needs to rebuild a whole microNotification
   * when recipients need the requester_id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value requester_id = 6;</code>
   * @return Whether the requesterId field is set.
   */
  boolean hasRequesterId();
  /**
   * <pre>
   * requester_id only exists when a requester triggers a notification to its recipients
   * Note: Do not move requester_id to microRequest because it needs to rebuild a whole microNotification
   * when recipients need the requester_id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value requester_id = 6;</code>
   * @return The requesterId.
   */
  com.google.protobuf.Int64Value getRequesterId();
  /**
   * <pre>
   * requester_id only exists when a requester triggers a notification to its recipients
   * Note: Do not move requester_id to microRequest because it needs to rebuild a whole microNotification
   * when recipients need the requester_id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value requester_id = 6;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getRequesterIdOrBuilder();
}
