// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/user/users_infos_with_version.proto

package im.micro.access.pojo.bo.user;

public interface UsersInfosWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.UsersInfosWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.micro.proto.UserInfo user_infos = 1;</code>
   */
  java.util.List<im.micro.access.pojo.bo.user.UserInfo> 
      getUserInfosList();
  /**
   * <code>repeated .im.micro.proto.UserInfo user_infos = 1;</code>
   */
  im.micro.access.pojo.bo.user.UserInfo getUserInfos(int index);
  /**
   * <code>repeated .im.micro.proto.UserInfo user_infos = 1;</code>
   */
  int getUserInfosCount();
  /**
   * <code>repeated .im.micro.proto.UserInfo user_infos = 1;</code>
   */
  java.util.List<? extends im.micro.access.pojo.bo.user.UserInfoOrBuilder> 
      getUserInfosOrBuilderList();
  /**
   * <code>repeated .im.micro.proto.UserInfo user_infos = 1;</code>
   */
  im.micro.access.pojo.bo.user.UserInfoOrBuilder getUserInfosOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
