// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/micro_request.proto

package im.micro.access.pojo.request;

public final class MicroRequestOuterClass {
  private MicroRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_micro_proto_MicroRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_micro_proto_MicroRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033request/micro_request.proto\022\016im.micro." +
      "proto\032\036google/protobuf/wrappers.proto\032 r" +
      "equest/signal/ack_request.proto\0327request" +
      "/user/query_user_group_invitations_reque" +
      "st.proto\032-request/user/query_user_profil" +
      "e_request.proto\0321request/user/query_user" +
      "s_ids_nearby_request.proto\0323request/user" +
      "/query_users_infos_nearby_request.proto\032" +
      "4request/user/query_users_online_status_" +
      "request.proto\032/request/user/update_user_" +
      "location_request.proto\0324request/user/upd" +
      "ate_user_online_status_request.proto\032&re" +
      "quest/user/update_user_request.proto\032=re" +
      "quest/user/relationship/create_friend_re" +
      "quest_request.proto\032Arequest/user/relati" +
      "onship/create_relationship_group_request" +
      ".proto\032;request/user/relationship/create" +
      "_relationship_request.proto\032Arequest/use" +
      "r/relationship/delete_relationship_group" +
      "_request.proto\032;request/user/relationshi" +
      "p/delete_relationship_request.proto\032=req" +
      "uest/user/relationship/query_friend_requ" +
      "ests_request.proto\032?request/user/relatio" +
      "nship/query_related_users_ids_request.pr" +
      "oto\032Arequest/user/relationship/query_rel" +
      "ationship_groups_request.proto\032;request/" +
      "user/relationship/query_relationships_re" +
      "quest.proto\032=request/user/relationship/u" +
      "pdate_friend_request_request.proto\032Arequ" +
      "est/user/relationship/update_relationshi" +
      "p_group_request.proto\032;request/user/rela" +
      "tionship/update_relationship_request.pro" +
      "to\032(request/group/create_group_request.p" +
      "roto\032(request/group/delete_group_request" +
      ".proto\032\'request/group/query_group_reques" +
      "t.proto\0323request/group/query_joined_grou" +
      "ps_ids_request.proto\0325request/group/quer" +
      "y_joined_groups_infos_request.proto\032(req" +
      "uest/group/update_group_request.proto\032Cr" +
      "equest/group/blacklist/create_group_blac" +
      "klisted_user_request.proto\032Crequest/grou" +
      "p/blacklist/delete_group_blacklisted_use" +
      "r_request.proto\032Grequest/group/blacklist" +
      "/query_group_blacklisted_users_ids_reque" +
      "st.proto\032Irequest/group/blacklist/query_" +
      "group_blacklisted_users_infos_request.pr" +
      "oto\032Irequest/group/enrollment/check_grou" +
      "p_join_questions_answers_request.proto\032>" +
      "request/group/enrollment/create_group_in" +
      "vitation_request.proto\032@request/group/en" +
      "rollment/create_group_join_request_reque" +
      "st.proto\032Arequest/group/enrollment/creat" +
      "e_group_join_question_request.proto\032>req" +
      "uest/group/enrollment/delete_group_invit" +
      "ation_request.proto\032@request/group/enrol" +
      "lment/delete_group_join_request_request." +
      "proto\032Arequest/group/enrollment/delete_g" +
      "roup_join_question_request.proto\032>reques" +
      "t/group/enrollment/query_group_invitatio" +
      "ns_request.proto\032@request/group/enrollme" +
      "nt/query_group_join_requests_request.pro" +
      "to\032Arequest/group/enrollment/query_group" +
      "_join_questions_request.proto\032Arequest/g" +
      "roup/enrollment/update_group_join_questi" +
      "on_request.proto\0326request/group/member/c" +
      "reate_group_member_request.proto\0326reques" +
      "t/group/member/delete_group_member_reque" +
      "st.proto\0326request/group/member/query_gro" +
      "up_members_request.proto\0326request/group/" +
      "member/update_group_member_request.proto" +
      "\032,request/message/create_message_request" +
      ".proto\0324request/message/query_message_st" +
      "atuses_request.proto\032,request/message/qu" +
      "ery_messages_request.proto\032?request/mess" +
      "age/query_pending_messages_with_total_re" +
      "quest.proto\032,request/message/update_mess" +
      "age_request.proto\0322request/message/updat" +
      "e_typing_status_request.proto\"\371#\n\014MicroR" +
      "equest\022/\n\nrequest_id\030\001 \001(\0132\033.google.prot" +
      "obuf.Int64Value\0221\n\013ack_request\030\002 \001(\0132\032.i" +
      "m.micro.proto.AckRequestH\000\022F\n\026create_mes" +
      "sage_request\030\005 \001(\0132$.im.micro.proto.Crea" +
      "teMessageRequestH\000\022U\n\036query_message_stat" +
      "uses_request\030\006 \001(\0132+.im.micro.proto.Quer" +
      "yMessageStatusesRequestH\000\022F\n\026query_messa" +
      "ges_request\030\007 \001(\0132$.im.micro.proto.Query" +
      "MessagesRequestH\000\022i\n)query_pending_messa" +
      "ges_with_total_request\030\010 \001(\01324.im.micro." +
      "proto.QueryPendingMessagesWithTotalReque" +
      "stH\000\022F\n\026update_message_request\030\t \001(\0132$.i" +
      "m.micro.proto.UpdateMessageRequestH\000\022Q\n\034" +
      "update_typing_status_request\030\n \001(\0132).im." +
      "micro.proto.UpdateTypingStatusRequestH\000\022" +
      "`\n$query_user_group_invitations_request\030" +
      "d \001(\01320.im.micro.proto.QueryUserGroupInv" +
      "itationsRequestH\000\022M\n\032query_user_profile_" +
      "request\030e \001(\0132\'.im.micro.proto.QueryUser" +
      "ProfileRequestH\000\022T\n\036query_users_ids_near" +
      "by_request\030f \001(\0132*.im.micro.proto.QueryU" +
      "sersIdsNearbyRequestH\000\022X\n query_users_in" +
      "fos_nearby_request\030g \001(\0132,.im.micro.prot" +
      "o.QueryUsersInfosNearbyRequestH\000\022Z\n!quer" +
      "y_users_online_status_request\030h \001(\0132-.im" +
      ".micro.proto.QueryUsersOnlineStatusReque" +
      "stH\000\022Q\n\034update_user_location_request\030i \001" +
      "(\0132).im.micro.proto.UpdateUserLocationRe" +
      "questH\000\022Z\n!update_user_online_status_req" +
      "uest\030j \001(\0132-.im.micro.proto.UpdateUserOn" +
      "lineStatusRequestH\000\022@\n\023update_user_reque" +
      "st\030k \001(\0132!.im.micro.proto.UpdateUserRequ" +
      "estH\000\022T\n\035create_friend_request_request\030\310" +
      "\001 \001(\0132*.im.micro.proto.CreateFriendReque" +
      "stRequestH\000\022\\\n!create_relationship_group" +
      "_request\030\311\001 \001(\0132..im.micro.proto.CreateR" +
      "elationshipGroupRequestH\000\022Q\n\033create_rela" +
      "tionship_request\030\312\001 \001(\0132).im.micro.proto" +
      ".CreateRelationshipRequestH\000\022\\\n!delete_r" +
      "elationship_group_request\030\313\001 \001(\0132..im.mi" +
      "cro.proto.DeleteRelationshipGroupRequest" +
      "H\000\022Q\n\033delete_relationship_request\030\314\001 \001(\013" +
      "2).im.micro.proto.DeleteRelationshipRequ" +
      "estH\000\022T\n\035query_friend_requests_request\030\315" +
      "\001 \001(\0132*.im.micro.proto.QueryFriendReques" +
      "tsRequestH\000\022W\n\037query_related_users_ids_r" +
      "equest\030\316\001 \001(\0132+.im.micro.proto.QueryRela" +
      "tedUsersIdsRequestH\000\022\\\n!query_relationsh" +
      "ip_groups_request\030\317\001 \001(\0132..im.micro.prot" +
      "o.QueryRelationshipGroupsRequestH\000\022Q\n\033qu" +
      "ery_relationships_request\030\320\001 \001(\0132).im.mi" +
      "cro.proto.QueryRelationshipsRequestH\000\022T\n" +
      "\035update_friend_request_request\030\321\001 \001(\0132*." +
      "im.micro.proto.UpdateFriendRequestReques" +
      "tH\000\022\\\n!update_relationship_group_request" +
      "\030\322\001 \001(\0132..im.micro.proto.UpdateRelations" +
      "hipGroupRequestH\000\022Q\n\033update_relationship" +
      "_request\030\323\001 \001(\0132).im.micro.proto.UpdateR" +
      "elationshipRequestH\000\022C\n\024create_group_req" +
      "uest\030\254\002 \001(\0132\".im.micro.proto.CreateGroup" +
      "RequestH\000\022C\n\024delete_group_request\030\255\002 \001(\013" +
      "2\".im.micro.proto.DeleteGroupRequestH\000\022A" +
      "\n\023query_group_request\030\256\002 \001(\0132!.im.micro." +
      "proto.QueryGroupRequestH\000\022W\n\037query_joine" +
      "d_groups_ids_request\030\257\002 \001(\0132+.im.micro.p" +
      "roto.QueryJoinedGroupsIdsRequestH\000\022[\n!qu" +
      "ery_joined_groups_infos_request\030\260\002 \001(\0132-" +
      ".im.micro.proto.QueryJoinedGroupsInfosRe" +
      "questH\000\022C\n\024update_group_request\030\261\002 \001(\0132\"" +
      ".im.micro.proto.UpdateGroupRequestH\000\022c\n%" +
      "create_group_blacklisted_user_request\030\220\003" +
      " \001(\01321.im.micro.proto.CreateGroupBlackli" +
      "stedUserRequestH\000\022c\n%delete_group_blackl" +
      "isted_user_request\030\221\003 \001(\01321.im.micro.pro" +
      "to.DeleteGroupBlacklistedUserRequestH\000\022j" +
      "\n)query_group_blacklisted_users_ids_requ" +
      "est\030\222\003 \001(\01324.im.micro.proto.QueryGroupBl" +
      "acklistedUsersIdsRequestH\000\022n\n+query_grou" +
      "p_blacklisted_users_infos_request\030\223\003 \001(\013" +
      "26.im.micro.proto.QueryGroupBlacklistedU" +
      "sersInfosRequestH\000\022l\n*check_group_join_q" +
      "uestions_answers_request\030\364\003 \001(\01325.im.mic" +
      "ro.proto.CheckGroupJoinQuestionsAnswersR" +
      "equestH\000\022X\n\037create_group_invitation_requ" +
      "est\030\365\003 \001(\0132,.im.micro.proto.CreateGroupI" +
      "nvitationRequestH\000\022[\n!create_group_join_" +
      "request_request\030\366\003 \001(\0132-.im.micro.proto." +
      "CreateGroupJoinRequestRequestH\000\022]\n\"creat" +
      "e_group_join_question_request\030\367\003 \001(\0132..i" +
      "m.micro.proto.CreateGroupJoinQuestionReq" +
      "uestH\000\022X\n\037delete_group_invitation_reques" +
      "t\030\370\003 \001(\0132,.im.micro.proto.DeleteGroupInv" +
      "itationRequestH\000\022[\n!delete_group_join_re" +
      "quest_request\030\371\003 \001(\0132-.im.micro.proto.De" +
      "leteGroupJoinRequestRequestH\000\022]\n\"delete_" +
      "group_join_question_request\030\372\003 \001(\0132..im." +
      "micro.proto.DeleteGroupJoinQuestionReque" +
      "stH\000\022X\n\037query_group_invitations_request\030" +
      "\373\003 \001(\0132,.im.micro.proto.QueryGroupInvita" +
      "tionsRequestH\000\022[\n!query_group_join_reque" +
      "sts_request\030\374\003 \001(\0132-.im.micro.proto.Quer" +
      "yGroupJoinRequestsRequestH\000\022]\n\"query_gro" +
      "up_join_questions_request\030\375\003 \001(\0132..im.mi" +
      "cro.proto.QueryGroupJoinQuestionsRequest" +
      "H\000\022]\n\"update_group_join_question_request" +
      "\030\376\003 \001(\0132..im.micro.proto.UpdateGroupJoin" +
      "QuestionRequestH\000\022P\n\033create_group_member" +
      "_request\030\330\004 \001(\0132(.im.micro.proto.CreateG" +
      "roupMemberRequestH\000\022P\n\033delete_group_memb" +
      "er_request\030\331\004 \001(\0132(.im.micro.proto.Delet" +
      "eGroupMemberRequestH\000\022P\n\033query_group_mem" +
      "bers_request\030\332\004 \001(\0132(.im.micro.proto.Que" +
      "ryGroupMembersRequestH\000\022P\n\033update_group_" +
      "member_request\030\333\004 \001(\0132(.im.micro.proto.U" +
      "pdateGroupMemberRequestH\000B\006\n\004kindB \n\034im." +
      "micro.access.pojo.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.micro.access.pojo.request.signal.AckRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.QueryUserGroupInvitationsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.QueryUserProfileRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.QueryUsersIdsNearbyRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.QueryUsersInfosNearbyRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.QueryUsersOnlineStatusRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.UpdateUserLocationRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.UpdateUserOnlineStatusRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.UpdateUserRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.CreateFriendRequestRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.CreateRelationshipGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.CreateRelationshipRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.DeleteRelationshipGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.DeleteRelationshipRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.QueryFriendRequestsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.QueryRelatedUsersIdsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.QueryRelationshipGroupsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.QueryRelationshipsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.UpdateFriendRequestRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.UpdateRelationshipGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.user.relationship.UpdateRelationshipRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.CreateGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.DeleteGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.QueryGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.QueryJoinedGroupsIdsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.QueryJoinedGroupsInfosRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.UpdateGroupRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.blacklist.CreateGroupBlacklistedUserRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.blacklist.DeleteGroupBlacklistedUserRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersIdsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersInfosRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.CheckGroupJoinQuestionsAnswersRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.CreateGroupInvitationRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.CreateGroupJoinRequestRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.CreateGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.DeleteGroupInvitationRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinRequestRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.QueryGroupInvitationsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.QueryGroupJoinRequestsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.QueryGroupJoinQuestionsRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.enrollment.UpdateGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.member.CreateGroupMemberRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.member.DeleteGroupMemberRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.member.QueryGroupMembersRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.group.member.UpdateGroupMemberRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.CreateMessageRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.QueryMessageStatusesRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.QueryMessagesRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.UpdateMessageRequestOuterClass.getDescriptor(),
          im.micro.access.pojo.request.message.UpdateTypingStatusRequestOuterClass.getDescriptor(),
        });
    internal_static_im_micro_proto_MicroRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_micro_proto_MicroRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_micro_proto_MicroRequest_descriptor,
        new java.lang.String[] { "RequestId", "AckRequest", "CreateMessageRequest", "QueryMessageStatusesRequest", "QueryMessagesRequest", "QueryPendingMessagesWithTotalRequest", "UpdateMessageRequest", "UpdateTypingStatusRequest", "QueryUserGroupInvitationsRequest", "QueryUserProfileRequest", "QueryUsersIdsNearbyRequest", "QueryUsersInfosNearbyRequest", "QueryUsersOnlineStatusRequest", "UpdateUserLocationRequest", "UpdateUserOnlineStatusRequest", "UpdateUserRequest", "CreateFriendRequestRequest", "CreateRelationshipGroupRequest", "CreateRelationshipRequest", "DeleteRelationshipGroupRequest", "DeleteRelationshipRequest", "QueryFriendRequestsRequest", "QueryRelatedUsersIdsRequest", "QueryRelationshipGroupsRequest", "QueryRelationshipsRequest", "UpdateFriendRequestRequest", "UpdateRelationshipGroupRequest", "UpdateRelationshipRequest", "CreateGroupRequest", "DeleteGroupRequest", "QueryGroupRequest", "QueryJoinedGroupsIdsRequest", "QueryJoinedGroupsInfosRequest", "UpdateGroupRequest", "CreateGroupBlacklistedUserRequest", "DeleteGroupBlacklistedUserRequest", "QueryGroupBlacklistedUsersIdsRequest", "QueryGroupBlacklistedUsersInfosRequest", "CheckGroupJoinQuestionsAnswersRequest", "CreateGroupInvitationRequest", "CreateGroupJoinRequestRequest", "CreateGroupJoinQuestionRequest", "DeleteGroupInvitationRequest", "DeleteGroupJoinRequestRequest", "DeleteGroupJoinQuestionRequest", "QueryGroupInvitationsRequest", "QueryGroupJoinRequestsRequest", "QueryGroupJoinQuestionsRequest", "UpdateGroupJoinQuestionRequest", "CreateGroupMemberRequest", "DeleteGroupMemberRequest", "QueryGroupMembersRequest", "UpdateGroupMemberRequest", "Kind", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.micro.access.pojo.request.signal.AckRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.QueryUserGroupInvitationsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.QueryUserProfileRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.QueryUsersIdsNearbyRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.QueryUsersInfosNearbyRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.QueryUsersOnlineStatusRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.UpdateUserLocationRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.UpdateUserOnlineStatusRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.UpdateUserRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.CreateFriendRequestRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.CreateRelationshipGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.CreateRelationshipRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.DeleteRelationshipGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.DeleteRelationshipRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.QueryFriendRequestsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.QueryRelatedUsersIdsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.QueryRelationshipGroupsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.QueryRelationshipsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.UpdateFriendRequestRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.UpdateRelationshipGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.user.relationship.UpdateRelationshipRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.CreateGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.DeleteGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.QueryGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.QueryJoinedGroupsIdsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.QueryJoinedGroupsInfosRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.UpdateGroupRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.blacklist.CreateGroupBlacklistedUserRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.blacklist.DeleteGroupBlacklistedUserRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersIdsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersInfosRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.CheckGroupJoinQuestionsAnswersRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.CreateGroupInvitationRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.CreateGroupJoinRequestRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.CreateGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.DeleteGroupInvitationRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinRequestRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.QueryGroupInvitationsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.QueryGroupJoinRequestsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.QueryGroupJoinQuestionsRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.enrollment.UpdateGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.member.CreateGroupMemberRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.member.DeleteGroupMemberRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.member.QueryGroupMembersRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.group.member.UpdateGroupMemberRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.CreateMessageRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.QueryMessageStatusesRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.QueryMessagesRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.UpdateMessageRequestOuterClass.getDescriptor();
    im.micro.access.pojo.request.message.UpdateTypingStatusRequestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
