// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/micro_request.proto

package im.micro.access.pojo.request;

public interface MicroRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.MicroRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   * @return Whether the requestId field is set.
   */
  boolean hasRequestId();
  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   * @return The requestId.
   */
  com.google.protobuf.Int64Value getRequestId();
  /**
   * <pre>
   * Note: request_id is allowed to be duplicate because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>.google.protobuf.Int64Value request_id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getRequestIdOrBuilder();

  /**
   * <pre>
   * Signal
   * </pre>
   *
   * <code>.im.micro.proto.AckRequest ack_request = 2;</code>
   * @return Whether the ackRequest field is set.
   */
  boolean hasAckRequest();
  /**
   * <pre>
   * Signal
   * </pre>
   *
   * <code>.im.micro.proto.AckRequest ack_request = 2;</code>
   * @return The ackRequest.
   */
  im.micro.access.pojo.request.signal.AckRequest getAckRequest();
  /**
   * <pre>
   * Signal
   * </pre>
   *
   * <code>.im.micro.proto.AckRequest ack_request = 2;</code>
   */
  im.micro.access.pojo.request.signal.AckRequestOrBuilder getAckRequestOrBuilder();

  /**
   * <pre>
   * Message
   * </pre>
   *
   * <code>.im.micro.proto.CreateMessageRequest create_message_request = 5;</code>
   * @return Whether the createMessageRequest field is set.
   */
  boolean hasCreateMessageRequest();
  /**
   * <pre>
   * Message
   * </pre>
   *
   * <code>.im.micro.proto.CreateMessageRequest create_message_request = 5;</code>
   * @return The createMessageRequest.
   */
  im.micro.access.pojo.request.message.CreateMessageRequest getCreateMessageRequest();
  /**
   * <pre>
   * Message
   * </pre>
   *
   * <code>.im.micro.proto.CreateMessageRequest create_message_request = 5;</code>
   */
  im.micro.access.pojo.request.message.CreateMessageRequestOrBuilder getCreateMessageRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryMessageStatusesRequest query_message_statuses_request = 6;</code>
   * @return Whether the queryMessageStatusesRequest field is set.
   */
  boolean hasQueryMessageStatusesRequest();
  /**
   * <code>.im.micro.proto.QueryMessageStatusesRequest query_message_statuses_request = 6;</code>
   * @return The queryMessageStatusesRequest.
   */
  im.micro.access.pojo.request.message.QueryMessageStatusesRequest getQueryMessageStatusesRequest();
  /**
   * <code>.im.micro.proto.QueryMessageStatusesRequest query_message_statuses_request = 6;</code>
   */
  im.micro.access.pojo.request.message.QueryMessageStatusesRequestOrBuilder getQueryMessageStatusesRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryMessagesRequest query_messages_request = 7;</code>
   * @return Whether the queryMessagesRequest field is set.
   */
  boolean hasQueryMessagesRequest();
  /**
   * <code>.im.micro.proto.QueryMessagesRequest query_messages_request = 7;</code>
   * @return The queryMessagesRequest.
   */
  im.micro.access.pojo.request.message.QueryMessagesRequest getQueryMessagesRequest();
  /**
   * <code>.im.micro.proto.QueryMessagesRequest query_messages_request = 7;</code>
   */
  im.micro.access.pojo.request.message.QueryMessagesRequestOrBuilder getQueryMessagesRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryPendingMessagesWithTotalRequest query_pending_messages_with_total_request = 8;</code>
   * @return Whether the queryPendingMessagesWithTotalRequest field is set.
   */
  boolean hasQueryPendingMessagesWithTotalRequest();
  /**
   * <code>.im.micro.proto.QueryPendingMessagesWithTotalRequest query_pending_messages_with_total_request = 8;</code>
   * @return The queryPendingMessagesWithTotalRequest.
   */
  im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest getQueryPendingMessagesWithTotalRequest();
  /**
   * <code>.im.micro.proto.QueryPendingMessagesWithTotalRequest query_pending_messages_with_total_request = 8;</code>
   */
  im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOrBuilder getQueryPendingMessagesWithTotalRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateMessageRequest update_message_request = 9;</code>
   * @return Whether the updateMessageRequest field is set.
   */
  boolean hasUpdateMessageRequest();
  /**
   * <code>.im.micro.proto.UpdateMessageRequest update_message_request = 9;</code>
   * @return The updateMessageRequest.
   */
  im.micro.access.pojo.request.message.UpdateMessageRequest getUpdateMessageRequest();
  /**
   * <code>.im.micro.proto.UpdateMessageRequest update_message_request = 9;</code>
   */
  im.micro.access.pojo.request.message.UpdateMessageRequestOrBuilder getUpdateMessageRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateTypingStatusRequest update_typing_status_request = 10;</code>
   * @return Whether the updateTypingStatusRequest field is set.
   */
  boolean hasUpdateTypingStatusRequest();
  /**
   * <code>.im.micro.proto.UpdateTypingStatusRequest update_typing_status_request = 10;</code>
   * @return The updateTypingStatusRequest.
   */
  im.micro.access.pojo.request.message.UpdateTypingStatusRequest getUpdateTypingStatusRequest();
  /**
   * <code>.im.micro.proto.UpdateTypingStatusRequest update_typing_status_request = 10;</code>
   */
  im.micro.access.pojo.request.message.UpdateTypingStatusRequestOrBuilder getUpdateTypingStatusRequestOrBuilder();

  /**
   * <pre>
   * User
   * </pre>
   *
   * <code>.im.micro.proto.QueryUserGroupInvitationsRequest query_user_group_invitations_request = 100;</code>
   * @return Whether the queryUserGroupInvitationsRequest field is set.
   */
  boolean hasQueryUserGroupInvitationsRequest();
  /**
   * <pre>
   * User
   * </pre>
   *
   * <code>.im.micro.proto.QueryUserGroupInvitationsRequest query_user_group_invitations_request = 100;</code>
   * @return The queryUserGroupInvitationsRequest.
   */
  im.micro.access.pojo.request.user.QueryUserGroupInvitationsRequest getQueryUserGroupInvitationsRequest();
  /**
   * <pre>
   * User
   * </pre>
   *
   * <code>.im.micro.proto.QueryUserGroupInvitationsRequest query_user_group_invitations_request = 100;</code>
   */
  im.micro.access.pojo.request.user.QueryUserGroupInvitationsRequestOrBuilder getQueryUserGroupInvitationsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryUserProfileRequest query_user_profile_request = 101;</code>
   * @return Whether the queryUserProfileRequest field is set.
   */
  boolean hasQueryUserProfileRequest();
  /**
   * <code>.im.micro.proto.QueryUserProfileRequest query_user_profile_request = 101;</code>
   * @return The queryUserProfileRequest.
   */
  im.micro.access.pojo.request.user.QueryUserProfileRequest getQueryUserProfileRequest();
  /**
   * <code>.im.micro.proto.QueryUserProfileRequest query_user_profile_request = 101;</code>
   */
  im.micro.access.pojo.request.user.QueryUserProfileRequestOrBuilder getQueryUserProfileRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryUsersIdsNearbyRequest query_users_ids_nearby_request = 102;</code>
   * @return Whether the queryUsersIdsNearbyRequest field is set.
   */
  boolean hasQueryUsersIdsNearbyRequest();
  /**
   * <code>.im.micro.proto.QueryUsersIdsNearbyRequest query_users_ids_nearby_request = 102;</code>
   * @return The queryUsersIdsNearbyRequest.
   */
  im.micro.access.pojo.request.user.QueryUsersIdsNearbyRequest getQueryUsersIdsNearbyRequest();
  /**
   * <code>.im.micro.proto.QueryUsersIdsNearbyRequest query_users_ids_nearby_request = 102;</code>
   */
  im.micro.access.pojo.request.user.QueryUsersIdsNearbyRequestOrBuilder getQueryUsersIdsNearbyRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryUsersInfosNearbyRequest query_users_infos_nearby_request = 103;</code>
   * @return Whether the queryUsersInfosNearbyRequest field is set.
   */
  boolean hasQueryUsersInfosNearbyRequest();
  /**
   * <code>.im.micro.proto.QueryUsersInfosNearbyRequest query_users_infos_nearby_request = 103;</code>
   * @return The queryUsersInfosNearbyRequest.
   */
  im.micro.access.pojo.request.user.QueryUsersInfosNearbyRequest getQueryUsersInfosNearbyRequest();
  /**
   * <code>.im.micro.proto.QueryUsersInfosNearbyRequest query_users_infos_nearby_request = 103;</code>
   */
  im.micro.access.pojo.request.user.QueryUsersInfosNearbyRequestOrBuilder getQueryUsersInfosNearbyRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryUsersOnlineStatusRequest query_users_online_status_request = 104;</code>
   * @return Whether the queryUsersOnlineStatusRequest field is set.
   */
  boolean hasQueryUsersOnlineStatusRequest();
  /**
   * <code>.im.micro.proto.QueryUsersOnlineStatusRequest query_users_online_status_request = 104;</code>
   * @return The queryUsersOnlineStatusRequest.
   */
  im.micro.access.pojo.request.user.QueryUsersOnlineStatusRequest getQueryUsersOnlineStatusRequest();
  /**
   * <code>.im.micro.proto.QueryUsersOnlineStatusRequest query_users_online_status_request = 104;</code>
   */
  im.micro.access.pojo.request.user.QueryUsersOnlineStatusRequestOrBuilder getQueryUsersOnlineStatusRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateUserLocationRequest update_user_location_request = 105;</code>
   * @return Whether the updateUserLocationRequest field is set.
   */
  boolean hasUpdateUserLocationRequest();
  /**
   * <code>.im.micro.proto.UpdateUserLocationRequest update_user_location_request = 105;</code>
   * @return The updateUserLocationRequest.
   */
  im.micro.access.pojo.request.user.UpdateUserLocationRequest getUpdateUserLocationRequest();
  /**
   * <code>.im.micro.proto.UpdateUserLocationRequest update_user_location_request = 105;</code>
   */
  im.micro.access.pojo.request.user.UpdateUserLocationRequestOrBuilder getUpdateUserLocationRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateUserOnlineStatusRequest update_user_online_status_request = 106;</code>
   * @return Whether the updateUserOnlineStatusRequest field is set.
   */
  boolean hasUpdateUserOnlineStatusRequest();
  /**
   * <code>.im.micro.proto.UpdateUserOnlineStatusRequest update_user_online_status_request = 106;</code>
   * @return The updateUserOnlineStatusRequest.
   */
  im.micro.access.pojo.request.user.UpdateUserOnlineStatusRequest getUpdateUserOnlineStatusRequest();
  /**
   * <code>.im.micro.proto.UpdateUserOnlineStatusRequest update_user_online_status_request = 106;</code>
   */
  im.micro.access.pojo.request.user.UpdateUserOnlineStatusRequestOrBuilder getUpdateUserOnlineStatusRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateUserRequest update_user_request = 107;</code>
   * @return Whether the updateUserRequest field is set.
   */
  boolean hasUpdateUserRequest();
  /**
   * <code>.im.micro.proto.UpdateUserRequest update_user_request = 107;</code>
   * @return The updateUserRequest.
   */
  im.micro.access.pojo.request.user.UpdateUserRequest getUpdateUserRequest();
  /**
   * <code>.im.micro.proto.UpdateUserRequest update_user_request = 107;</code>
   */
  im.micro.access.pojo.request.user.UpdateUserRequestOrBuilder getUpdateUserRequestOrBuilder();

  /**
   * <pre>
   * User Relationship
   * </pre>
   *
   * <code>.im.micro.proto.CreateFriendRequestRequest create_friend_request_request = 200;</code>
   * @return Whether the createFriendRequestRequest field is set.
   */
  boolean hasCreateFriendRequestRequest();
  /**
   * <pre>
   * User Relationship
   * </pre>
   *
   * <code>.im.micro.proto.CreateFriendRequestRequest create_friend_request_request = 200;</code>
   * @return The createFriendRequestRequest.
   */
  im.micro.access.pojo.request.user.relationship.CreateFriendRequestRequest getCreateFriendRequestRequest();
  /**
   * <pre>
   * User Relationship
   * </pre>
   *
   * <code>.im.micro.proto.CreateFriendRequestRequest create_friend_request_request = 200;</code>
   */
  im.micro.access.pojo.request.user.relationship.CreateFriendRequestRequestOrBuilder getCreateFriendRequestRequestOrBuilder();

  /**
   * <code>.im.micro.proto.CreateRelationshipGroupRequest create_relationship_group_request = 201;</code>
   * @return Whether the createRelationshipGroupRequest field is set.
   */
  boolean hasCreateRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.CreateRelationshipGroupRequest create_relationship_group_request = 201;</code>
   * @return The createRelationshipGroupRequest.
   */
  im.micro.access.pojo.request.user.relationship.CreateRelationshipGroupRequest getCreateRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.CreateRelationshipGroupRequest create_relationship_group_request = 201;</code>
   */
  im.micro.access.pojo.request.user.relationship.CreateRelationshipGroupRequestOrBuilder getCreateRelationshipGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.CreateRelationshipRequest create_relationship_request = 202;</code>
   * @return Whether the createRelationshipRequest field is set.
   */
  boolean hasCreateRelationshipRequest();
  /**
   * <code>.im.micro.proto.CreateRelationshipRequest create_relationship_request = 202;</code>
   * @return The createRelationshipRequest.
   */
  im.micro.access.pojo.request.user.relationship.CreateRelationshipRequest getCreateRelationshipRequest();
  /**
   * <code>.im.micro.proto.CreateRelationshipRequest create_relationship_request = 202;</code>
   */
  im.micro.access.pojo.request.user.relationship.CreateRelationshipRequestOrBuilder getCreateRelationshipRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteRelationshipGroupRequest delete_relationship_group_request = 203;</code>
   * @return Whether the deleteRelationshipGroupRequest field is set.
   */
  boolean hasDeleteRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.DeleteRelationshipGroupRequest delete_relationship_group_request = 203;</code>
   * @return The deleteRelationshipGroupRequest.
   */
  im.micro.access.pojo.request.user.relationship.DeleteRelationshipGroupRequest getDeleteRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.DeleteRelationshipGroupRequest delete_relationship_group_request = 203;</code>
   */
  im.micro.access.pojo.request.user.relationship.DeleteRelationshipGroupRequestOrBuilder getDeleteRelationshipGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteRelationshipRequest delete_relationship_request = 204;</code>
   * @return Whether the deleteRelationshipRequest field is set.
   */
  boolean hasDeleteRelationshipRequest();
  /**
   * <code>.im.micro.proto.DeleteRelationshipRequest delete_relationship_request = 204;</code>
   * @return The deleteRelationshipRequest.
   */
  im.micro.access.pojo.request.user.relationship.DeleteRelationshipRequest getDeleteRelationshipRequest();
  /**
   * <code>.im.micro.proto.DeleteRelationshipRequest delete_relationship_request = 204;</code>
   */
  im.micro.access.pojo.request.user.relationship.DeleteRelationshipRequestOrBuilder getDeleteRelationshipRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryFriendRequestsRequest query_friend_requests_request = 205;</code>
   * @return Whether the queryFriendRequestsRequest field is set.
   */
  boolean hasQueryFriendRequestsRequest();
  /**
   * <code>.im.micro.proto.QueryFriendRequestsRequest query_friend_requests_request = 205;</code>
   * @return The queryFriendRequestsRequest.
   */
  im.micro.access.pojo.request.user.relationship.QueryFriendRequestsRequest getQueryFriendRequestsRequest();
  /**
   * <code>.im.micro.proto.QueryFriendRequestsRequest query_friend_requests_request = 205;</code>
   */
  im.micro.access.pojo.request.user.relationship.QueryFriendRequestsRequestOrBuilder getQueryFriendRequestsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryRelatedUsersIdsRequest query_related_users_ids_request = 206;</code>
   * @return Whether the queryRelatedUsersIdsRequest field is set.
   */
  boolean hasQueryRelatedUsersIdsRequest();
  /**
   * <code>.im.micro.proto.QueryRelatedUsersIdsRequest query_related_users_ids_request = 206;</code>
   * @return The queryRelatedUsersIdsRequest.
   */
  im.micro.access.pojo.request.user.relationship.QueryRelatedUsersIdsRequest getQueryRelatedUsersIdsRequest();
  /**
   * <code>.im.micro.proto.QueryRelatedUsersIdsRequest query_related_users_ids_request = 206;</code>
   */
  im.micro.access.pojo.request.user.relationship.QueryRelatedUsersIdsRequestOrBuilder getQueryRelatedUsersIdsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryRelationshipGroupsRequest query_relationship_groups_request = 207;</code>
   * @return Whether the queryRelationshipGroupsRequest field is set.
   */
  boolean hasQueryRelationshipGroupsRequest();
  /**
   * <code>.im.micro.proto.QueryRelationshipGroupsRequest query_relationship_groups_request = 207;</code>
   * @return The queryRelationshipGroupsRequest.
   */
  im.micro.access.pojo.request.user.relationship.QueryRelationshipGroupsRequest getQueryRelationshipGroupsRequest();
  /**
   * <code>.im.micro.proto.QueryRelationshipGroupsRequest query_relationship_groups_request = 207;</code>
   */
  im.micro.access.pojo.request.user.relationship.QueryRelationshipGroupsRequestOrBuilder getQueryRelationshipGroupsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryRelationshipsRequest query_relationships_request = 208;</code>
   * @return Whether the queryRelationshipsRequest field is set.
   */
  boolean hasQueryRelationshipsRequest();
  /**
   * <code>.im.micro.proto.QueryRelationshipsRequest query_relationships_request = 208;</code>
   * @return The queryRelationshipsRequest.
   */
  im.micro.access.pojo.request.user.relationship.QueryRelationshipsRequest getQueryRelationshipsRequest();
  /**
   * <code>.im.micro.proto.QueryRelationshipsRequest query_relationships_request = 208;</code>
   */
  im.micro.access.pojo.request.user.relationship.QueryRelationshipsRequestOrBuilder getQueryRelationshipsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateFriendRequestRequest update_friend_request_request = 209;</code>
   * @return Whether the updateFriendRequestRequest field is set.
   */
  boolean hasUpdateFriendRequestRequest();
  /**
   * <code>.im.micro.proto.UpdateFriendRequestRequest update_friend_request_request = 209;</code>
   * @return The updateFriendRequestRequest.
   */
  im.micro.access.pojo.request.user.relationship.UpdateFriendRequestRequest getUpdateFriendRequestRequest();
  /**
   * <code>.im.micro.proto.UpdateFriendRequestRequest update_friend_request_request = 209;</code>
   */
  im.micro.access.pojo.request.user.relationship.UpdateFriendRequestRequestOrBuilder getUpdateFriendRequestRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateRelationshipGroupRequest update_relationship_group_request = 210;</code>
   * @return Whether the updateRelationshipGroupRequest field is set.
   */
  boolean hasUpdateRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.UpdateRelationshipGroupRequest update_relationship_group_request = 210;</code>
   * @return The updateRelationshipGroupRequest.
   */
  im.micro.access.pojo.request.user.relationship.UpdateRelationshipGroupRequest getUpdateRelationshipGroupRequest();
  /**
   * <code>.im.micro.proto.UpdateRelationshipGroupRequest update_relationship_group_request = 210;</code>
   */
  im.micro.access.pojo.request.user.relationship.UpdateRelationshipGroupRequestOrBuilder getUpdateRelationshipGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateRelationshipRequest update_relationship_request = 211;</code>
   * @return Whether the updateRelationshipRequest field is set.
   */
  boolean hasUpdateRelationshipRequest();
  /**
   * <code>.im.micro.proto.UpdateRelationshipRequest update_relationship_request = 211;</code>
   * @return The updateRelationshipRequest.
   */
  im.micro.access.pojo.request.user.relationship.UpdateRelationshipRequest getUpdateRelationshipRequest();
  /**
   * <code>.im.micro.proto.UpdateRelationshipRequest update_relationship_request = 211;</code>
   */
  im.micro.access.pojo.request.user.relationship.UpdateRelationshipRequestOrBuilder getUpdateRelationshipRequestOrBuilder();

  /**
   * <pre>
   * Group
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupRequest create_group_request = 300;</code>
   * @return Whether the createGroupRequest field is set.
   */
  boolean hasCreateGroupRequest();
  /**
   * <pre>
   * Group
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupRequest create_group_request = 300;</code>
   * @return The createGroupRequest.
   */
  im.micro.access.pojo.request.group.CreateGroupRequest getCreateGroupRequest();
  /**
   * <pre>
   * Group
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupRequest create_group_request = 300;</code>
   */
  im.micro.access.pojo.request.group.CreateGroupRequestOrBuilder getCreateGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupRequest delete_group_request = 301;</code>
   * @return Whether the deleteGroupRequest field is set.
   */
  boolean hasDeleteGroupRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupRequest delete_group_request = 301;</code>
   * @return The deleteGroupRequest.
   */
  im.micro.access.pojo.request.group.DeleteGroupRequest getDeleteGroupRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupRequest delete_group_request = 301;</code>
   */
  im.micro.access.pojo.request.group.DeleteGroupRequestOrBuilder getDeleteGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupRequest query_group_request = 302;</code>
   * @return Whether the queryGroupRequest field is set.
   */
  boolean hasQueryGroupRequest();
  /**
   * <code>.im.micro.proto.QueryGroupRequest query_group_request = 302;</code>
   * @return The queryGroupRequest.
   */
  im.micro.access.pojo.request.group.QueryGroupRequest getQueryGroupRequest();
  /**
   * <code>.im.micro.proto.QueryGroupRequest query_group_request = 302;</code>
   */
  im.micro.access.pojo.request.group.QueryGroupRequestOrBuilder getQueryGroupRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryJoinedGroupsIdsRequest query_joined_groups_ids_request = 303;</code>
   * @return Whether the queryJoinedGroupsIdsRequest field is set.
   */
  boolean hasQueryJoinedGroupsIdsRequest();
  /**
   * <code>.im.micro.proto.QueryJoinedGroupsIdsRequest query_joined_groups_ids_request = 303;</code>
   * @return The queryJoinedGroupsIdsRequest.
   */
  im.micro.access.pojo.request.group.QueryJoinedGroupsIdsRequest getQueryJoinedGroupsIdsRequest();
  /**
   * <code>.im.micro.proto.QueryJoinedGroupsIdsRequest query_joined_groups_ids_request = 303;</code>
   */
  im.micro.access.pojo.request.group.QueryJoinedGroupsIdsRequestOrBuilder getQueryJoinedGroupsIdsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryJoinedGroupsInfosRequest query_joined_groups_infos_request = 304;</code>
   * @return Whether the queryJoinedGroupsInfosRequest field is set.
   */
  boolean hasQueryJoinedGroupsInfosRequest();
  /**
   * <code>.im.micro.proto.QueryJoinedGroupsInfosRequest query_joined_groups_infos_request = 304;</code>
   * @return The queryJoinedGroupsInfosRequest.
   */
  im.micro.access.pojo.request.group.QueryJoinedGroupsInfosRequest getQueryJoinedGroupsInfosRequest();
  /**
   * <code>.im.micro.proto.QueryJoinedGroupsInfosRequest query_joined_groups_infos_request = 304;</code>
   */
  im.micro.access.pojo.request.group.QueryJoinedGroupsInfosRequestOrBuilder getQueryJoinedGroupsInfosRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateGroupRequest update_group_request = 305;</code>
   * @return Whether the updateGroupRequest field is set.
   */
  boolean hasUpdateGroupRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupRequest update_group_request = 305;</code>
   * @return The updateGroupRequest.
   */
  im.micro.access.pojo.request.group.UpdateGroupRequest getUpdateGroupRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupRequest update_group_request = 305;</code>
   */
  im.micro.access.pojo.request.group.UpdateGroupRequestOrBuilder getUpdateGroupRequestOrBuilder();

  /**
   * <pre>
   * Group Blacklist
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupBlacklistedUserRequest create_group_blacklisted_user_request = 400;</code>
   * @return Whether the createGroupBlacklistedUserRequest field is set.
   */
  boolean hasCreateGroupBlacklistedUserRequest();
  /**
   * <pre>
   * Group Blacklist
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupBlacklistedUserRequest create_group_blacklisted_user_request = 400;</code>
   * @return The createGroupBlacklistedUserRequest.
   */
  im.micro.access.pojo.request.group.blacklist.CreateGroupBlacklistedUserRequest getCreateGroupBlacklistedUserRequest();
  /**
   * <pre>
   * Group Blacklist
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupBlacklistedUserRequest create_group_blacklisted_user_request = 400;</code>
   */
  im.micro.access.pojo.request.group.blacklist.CreateGroupBlacklistedUserRequestOrBuilder getCreateGroupBlacklistedUserRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupBlacklistedUserRequest delete_group_blacklisted_user_request = 401;</code>
   * @return Whether the deleteGroupBlacklistedUserRequest field is set.
   */
  boolean hasDeleteGroupBlacklistedUserRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupBlacklistedUserRequest delete_group_blacklisted_user_request = 401;</code>
   * @return The deleteGroupBlacklistedUserRequest.
   */
  im.micro.access.pojo.request.group.blacklist.DeleteGroupBlacklistedUserRequest getDeleteGroupBlacklistedUserRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupBlacklistedUserRequest delete_group_blacklisted_user_request = 401;</code>
   */
  im.micro.access.pojo.request.group.blacklist.DeleteGroupBlacklistedUserRequestOrBuilder getDeleteGroupBlacklistedUserRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersIdsRequest query_group_blacklisted_users_ids_request = 402;</code>
   * @return Whether the queryGroupBlacklistedUsersIdsRequest field is set.
   */
  boolean hasQueryGroupBlacklistedUsersIdsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersIdsRequest query_group_blacklisted_users_ids_request = 402;</code>
   * @return The queryGroupBlacklistedUsersIdsRequest.
   */
  im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersIdsRequest getQueryGroupBlacklistedUsersIdsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersIdsRequest query_group_blacklisted_users_ids_request = 402;</code>
   */
  im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersIdsRequestOrBuilder getQueryGroupBlacklistedUsersIdsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersInfosRequest query_group_blacklisted_users_infos_request = 403;</code>
   * @return Whether the queryGroupBlacklistedUsersInfosRequest field is set.
   */
  boolean hasQueryGroupBlacklistedUsersInfosRequest();
  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersInfosRequest query_group_blacklisted_users_infos_request = 403;</code>
   * @return The queryGroupBlacklistedUsersInfosRequest.
   */
  im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersInfosRequest getQueryGroupBlacklistedUsersInfosRequest();
  /**
   * <code>.im.micro.proto.QueryGroupBlacklistedUsersInfosRequest query_group_blacklisted_users_infos_request = 403;</code>
   */
  im.micro.access.pojo.request.group.blacklist.QueryGroupBlacklistedUsersInfosRequestOrBuilder getQueryGroupBlacklistedUsersInfosRequestOrBuilder();

  /**
   * <pre>
   * Group Enrollment
   * </pre>
   *
   * <code>.im.micro.proto.CheckGroupJoinQuestionsAnswersRequest check_group_join_questions_answers_request = 500;</code>
   * @return Whether the checkGroupJoinQuestionsAnswersRequest field is set.
   */
  boolean hasCheckGroupJoinQuestionsAnswersRequest();
  /**
   * <pre>
   * Group Enrollment
   * </pre>
   *
   * <code>.im.micro.proto.CheckGroupJoinQuestionsAnswersRequest check_group_join_questions_answers_request = 500;</code>
   * @return The checkGroupJoinQuestionsAnswersRequest.
   */
  im.micro.access.pojo.request.group.enrollment.CheckGroupJoinQuestionsAnswersRequest getCheckGroupJoinQuestionsAnswersRequest();
  /**
   * <pre>
   * Group Enrollment
   * </pre>
   *
   * <code>.im.micro.proto.CheckGroupJoinQuestionsAnswersRequest check_group_join_questions_answers_request = 500;</code>
   */
  im.micro.access.pojo.request.group.enrollment.CheckGroupJoinQuestionsAnswersRequestOrBuilder getCheckGroupJoinQuestionsAnswersRequestOrBuilder();

  /**
   * <code>.im.micro.proto.CreateGroupInvitationRequest create_group_invitation_request = 501;</code>
   * @return Whether the createGroupInvitationRequest field is set.
   */
  boolean hasCreateGroupInvitationRequest();
  /**
   * <code>.im.micro.proto.CreateGroupInvitationRequest create_group_invitation_request = 501;</code>
   * @return The createGroupInvitationRequest.
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupInvitationRequest getCreateGroupInvitationRequest();
  /**
   * <code>.im.micro.proto.CreateGroupInvitationRequest create_group_invitation_request = 501;</code>
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupInvitationRequestOrBuilder getCreateGroupInvitationRequestOrBuilder();

  /**
   * <code>.im.micro.proto.CreateGroupJoinRequestRequest create_group_join_request_request = 502;</code>
   * @return Whether the createGroupJoinRequestRequest field is set.
   */
  boolean hasCreateGroupJoinRequestRequest();
  /**
   * <code>.im.micro.proto.CreateGroupJoinRequestRequest create_group_join_request_request = 502;</code>
   * @return The createGroupJoinRequestRequest.
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupJoinRequestRequest getCreateGroupJoinRequestRequest();
  /**
   * <code>.im.micro.proto.CreateGroupJoinRequestRequest create_group_join_request_request = 502;</code>
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupJoinRequestRequestOrBuilder getCreateGroupJoinRequestRequestOrBuilder();

  /**
   * <code>.im.micro.proto.CreateGroupJoinQuestionRequest create_group_join_question_request = 503;</code>
   * @return Whether the createGroupJoinQuestionRequest field is set.
   */
  boolean hasCreateGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.CreateGroupJoinQuestionRequest create_group_join_question_request = 503;</code>
   * @return The createGroupJoinQuestionRequest.
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupJoinQuestionRequest getCreateGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.CreateGroupJoinQuestionRequest create_group_join_question_request = 503;</code>
   */
  im.micro.access.pojo.request.group.enrollment.CreateGroupJoinQuestionRequestOrBuilder getCreateGroupJoinQuestionRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupInvitationRequest delete_group_invitation_request = 504;</code>
   * @return Whether the deleteGroupInvitationRequest field is set.
   */
  boolean hasDeleteGroupInvitationRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupInvitationRequest delete_group_invitation_request = 504;</code>
   * @return The deleteGroupInvitationRequest.
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupInvitationRequest getDeleteGroupInvitationRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupInvitationRequest delete_group_invitation_request = 504;</code>
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupInvitationRequestOrBuilder getDeleteGroupInvitationRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupJoinRequestRequest delete_group_join_request_request = 505;</code>
   * @return Whether the deleteGroupJoinRequestRequest field is set.
   */
  boolean hasDeleteGroupJoinRequestRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupJoinRequestRequest delete_group_join_request_request = 505;</code>
   * @return The deleteGroupJoinRequestRequest.
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinRequestRequest getDeleteGroupJoinRequestRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupJoinRequestRequest delete_group_join_request_request = 505;</code>
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinRequestRequestOrBuilder getDeleteGroupJoinRequestRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupJoinQuestionRequest delete_group_join_question_request = 506;</code>
   * @return Whether the deleteGroupJoinQuestionRequest field is set.
   */
  boolean hasDeleteGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupJoinQuestionRequest delete_group_join_question_request = 506;</code>
   * @return The deleteGroupJoinQuestionRequest.
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinQuestionRequest getDeleteGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupJoinQuestionRequest delete_group_join_question_request = 506;</code>
   */
  im.micro.access.pojo.request.group.enrollment.DeleteGroupJoinQuestionRequestOrBuilder getDeleteGroupJoinQuestionRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupInvitationsRequest query_group_invitations_request = 507;</code>
   * @return Whether the queryGroupInvitationsRequest field is set.
   */
  boolean hasQueryGroupInvitationsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupInvitationsRequest query_group_invitations_request = 507;</code>
   * @return The queryGroupInvitationsRequest.
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupInvitationsRequest getQueryGroupInvitationsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupInvitationsRequest query_group_invitations_request = 507;</code>
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupInvitationsRequestOrBuilder getQueryGroupInvitationsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupJoinRequestsRequest query_group_join_requests_request = 508;</code>
   * @return Whether the queryGroupJoinRequestsRequest field is set.
   */
  boolean hasQueryGroupJoinRequestsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupJoinRequestsRequest query_group_join_requests_request = 508;</code>
   * @return The queryGroupJoinRequestsRequest.
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupJoinRequestsRequest getQueryGroupJoinRequestsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupJoinRequestsRequest query_group_join_requests_request = 508;</code>
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupJoinRequestsRequestOrBuilder getQueryGroupJoinRequestsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupJoinQuestionsRequest query_group_join_questions_request = 509;</code>
   * @return Whether the queryGroupJoinQuestionsRequest field is set.
   */
  boolean hasQueryGroupJoinQuestionsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupJoinQuestionsRequest query_group_join_questions_request = 509;</code>
   * @return The queryGroupJoinQuestionsRequest.
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupJoinQuestionsRequest getQueryGroupJoinQuestionsRequest();
  /**
   * <code>.im.micro.proto.QueryGroupJoinQuestionsRequest query_group_join_questions_request = 509;</code>
   */
  im.micro.access.pojo.request.group.enrollment.QueryGroupJoinQuestionsRequestOrBuilder getQueryGroupJoinQuestionsRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateGroupJoinQuestionRequest update_group_join_question_request = 510;</code>
   * @return Whether the updateGroupJoinQuestionRequest field is set.
   */
  boolean hasUpdateGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupJoinQuestionRequest update_group_join_question_request = 510;</code>
   * @return The updateGroupJoinQuestionRequest.
   */
  im.micro.access.pojo.request.group.enrollment.UpdateGroupJoinQuestionRequest getUpdateGroupJoinQuestionRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupJoinQuestionRequest update_group_join_question_request = 510;</code>
   */
  im.micro.access.pojo.request.group.enrollment.UpdateGroupJoinQuestionRequestOrBuilder getUpdateGroupJoinQuestionRequestOrBuilder();

  /**
   * <pre>
   * Group Member
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupMemberRequest create_group_member_request = 600;</code>
   * @return Whether the createGroupMemberRequest field is set.
   */
  boolean hasCreateGroupMemberRequest();
  /**
   * <pre>
   * Group Member
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupMemberRequest create_group_member_request = 600;</code>
   * @return The createGroupMemberRequest.
   */
  im.micro.access.pojo.request.group.member.CreateGroupMemberRequest getCreateGroupMemberRequest();
  /**
   * <pre>
   * Group Member
   * </pre>
   *
   * <code>.im.micro.proto.CreateGroupMemberRequest create_group_member_request = 600;</code>
   */
  im.micro.access.pojo.request.group.member.CreateGroupMemberRequestOrBuilder getCreateGroupMemberRequestOrBuilder();

  /**
   * <code>.im.micro.proto.DeleteGroupMemberRequest delete_group_member_request = 601;</code>
   * @return Whether the deleteGroupMemberRequest field is set.
   */
  boolean hasDeleteGroupMemberRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupMemberRequest delete_group_member_request = 601;</code>
   * @return The deleteGroupMemberRequest.
   */
  im.micro.access.pojo.request.group.member.DeleteGroupMemberRequest getDeleteGroupMemberRequest();
  /**
   * <code>.im.micro.proto.DeleteGroupMemberRequest delete_group_member_request = 601;</code>
   */
  im.micro.access.pojo.request.group.member.DeleteGroupMemberRequestOrBuilder getDeleteGroupMemberRequestOrBuilder();

  /**
   * <code>.im.micro.proto.QueryGroupMembersRequest query_group_members_request = 602;</code>
   * @return Whether the queryGroupMembersRequest field is set.
   */
  boolean hasQueryGroupMembersRequest();
  /**
   * <code>.im.micro.proto.QueryGroupMembersRequest query_group_members_request = 602;</code>
   * @return The queryGroupMembersRequest.
   */
  im.micro.access.pojo.request.group.member.QueryGroupMembersRequest getQueryGroupMembersRequest();
  /**
   * <code>.im.micro.proto.QueryGroupMembersRequest query_group_members_request = 602;</code>
   */
  im.micro.access.pojo.request.group.member.QueryGroupMembersRequestOrBuilder getQueryGroupMembersRequestOrBuilder();

  /**
   * <code>.im.micro.proto.UpdateGroupMemberRequest update_group_member_request = 603;</code>
   * @return Whether the updateGroupMemberRequest field is set.
   */
  boolean hasUpdateGroupMemberRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupMemberRequest update_group_member_request = 603;</code>
   * @return The updateGroupMemberRequest.
   */
  im.micro.access.pojo.request.group.member.UpdateGroupMemberRequest getUpdateGroupMemberRequest();
  /**
   * <code>.im.micro.proto.UpdateGroupMemberRequest update_group_member_request = 603;</code>
   */
  im.micro.access.pojo.request.group.member.UpdateGroupMemberRequestOrBuilder getUpdateGroupMemberRequestOrBuilder();

  public im.micro.access.pojo.request.MicroRequest.KindCase getKindCase();
}
