// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/signal/acknowledge.proto

package im.micro.access.pojo.bo.signal;

public interface AcknowledgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.Acknowledge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 delivery_date = 1;</code>
   * @return The deliveryDate.
   */
  long getDeliveryDate();

  /**
   * <code>.google.protobuf.Int64Value message_id = 2;</code>
   * @return Whether the messageId field is set.
   */
  boolean hasMessageId();
  /**
   * <code>.google.protobuf.Int64Value message_id = 2;</code>
   * @return The messageId.
   */
  com.google.protobuf.Int64Value getMessageId();
  /**
   * <code>.google.protobuf.Int64Value message_id = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getMessageIdOrBuilder();
}
