// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constant/message_delivery_status.proto

package im.micro.access.constant;

public final class MessageDeliveryStatusOuterClass {
  private MessageDeliveryStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&constant/message_delivery_status.proto" +
      "\022\016im.micro.proto*Z\n\025MessageDeliveryStatu" +
      "s\022\t\n\005READY\020\000\022\013\n\007SENDING\020\001\022\014\n\010RECEIVED\020\002\022" +
      "\r\n\tRECALLING\020\003\022\014\n\010RECALLED\020\004B\034\n\030im.micro" +
      ".access.constantP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
