// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constant/message_delivery_status.proto

package im.micro.access.constant;

/**
 * <pre>
 * 消息投送状态
 * </pre>
 *
 * Protobuf enum {@code im.micro.proto.MessageDeliveryStatus}
 */
public enum MessageDeliveryStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *准备发送
   * </pre>
   *
   * <code>READY = 0;</code>
   */
  READY(0),
  /**
   * <pre>
   * 正在发送
   * </pre>
   *
   * <code>SENDING = 1;</code>
   */
  SENDING(1),
  /**
   * <pre>
   * 已送达
   * </pre>
   *
   * <code>RECEIVED = 2;</code>
   */
  RECEIVED(2),
  /**
   * <pre>
   * 回复中
   * </pre>
   *
   * <code>RECALLING = 3;</code>
   */
  RECALLING(3),
  /**
   * <pre>
   * 已回复
   * </pre>
   *
   * <code>RECALLED = 4;</code>
   */
  RECALLED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *准备发送
   * </pre>
   *
   * <code>READY = 0;</code>
   */
  public static final int READY_VALUE = 0;
  /**
   * <pre>
   * 正在发送
   * </pre>
   *
   * <code>SENDING = 1;</code>
   */
  public static final int SENDING_VALUE = 1;
  /**
   * <pre>
   * 已送达
   * </pre>
   *
   * <code>RECEIVED = 2;</code>
   */
  public static final int RECEIVED_VALUE = 2;
  /**
   * <pre>
   * 回复中
   * </pre>
   *
   * <code>RECALLING = 3;</code>
   */
  public static final int RECALLING_VALUE = 3;
  /**
   * <pre>
   * 已回复
   * </pre>
   *
   * <code>RECALLED = 4;</code>
   */
  public static final int RECALLED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageDeliveryStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageDeliveryStatus forNumber(int value) {
    switch (value) {
      case 0: return READY;
      case 1: return SENDING;
      case 2: return RECEIVED;
      case 3: return RECALLING;
      case 4: return RECALLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageDeliveryStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageDeliveryStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageDeliveryStatus>() {
          public MessageDeliveryStatus findValueByNumber(int number) {
            return MessageDeliveryStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return im.micro.access.constant.MessageDeliveryStatusOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageDeliveryStatus[] VALUES = values();

  public static MessageDeliveryStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageDeliveryStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:im.micro.proto.MessageDeliveryStatus)
}

