// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/relationship/query_related_users_ids_request.proto

package im.micro.access.pojo.request.user.relationship;

public final class QueryRelatedUsersIdsRequestOuterClass {
  private QueryRelatedUsersIdsRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_micro_proto_QueryRelatedUsersIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_micro_proto_QueryRelatedUsersIdsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?request/user/relationship/query_relate" +
      "d_users_ids_request.proto\022\016im.micro.prot" +
      "o\032\036google/protobuf/wrappers.proto\"\267\001\n\033Qu" +
      "eryRelatedUsersIdsRequest\022.\n\nis_blocked\030" +
      "\001 \001(\0132\032.google.protobuf.BoolValue\0220\n\013gro" +
      "up_index\030\002 \001(\0132\033.google.protobuf.Int32Va" +
      "lue\0226\n\021last_updated_date\030\003 \001(\0132\033.google." +
      "protobuf.Int64ValueB2\n.im.micro.access.p" +
      "ojo.request.user.relationshipP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_micro_proto_QueryRelatedUsersIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_micro_proto_QueryRelatedUsersIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_micro_proto_QueryRelatedUsersIdsRequest_descriptor,
        new java.lang.String[] { "IsBlocked", "GroupIndex", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
