// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/signal/ack_request.proto

package im.micro.access.pojo.request.signal;

/**
 * Protobuf type {@code im.turms.proto.AckRequest}
 */
public  final class AckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.AckRequest)
    AckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AckRequest.newBuilder() to construct.
  private AckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AckRequest() {
    messagesIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AckRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messagesIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            messagesIds_.addLong(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              messagesIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              messagesIds_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messagesIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.micro.access.pojo.request.signal.AckRequestOuterClass.internal_static_im_turms_proto_AckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.micro.access.pojo.request.signal.AckRequestOuterClass.internal_static_im_turms_proto_AckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.micro.access.pojo.request.signal.AckRequest.class, im.micro.access.pojo.request.signal.AckRequest.Builder.class);
  }

  public static final int MESSAGES_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList messagesIds_;
  /**
   * <code>repeated int64 messages_ids = 1;</code>
   * @return A list containing the messagesIds.
   */
  public java.util.List<java.lang.Long>
      getMessagesIdsList() {
    return messagesIds_;
  }
  /**
   * <code>repeated int64 messages_ids = 1;</code>
   * @return The count of messagesIds.
   */
  public int getMessagesIdsCount() {
    return messagesIds_.size();
  }
  /**
   * <code>repeated int64 messages_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The messagesIds at the given index.
   */
  public long getMessagesIds(int index) {
    return messagesIds_.getLong(index);
  }
  private int messagesIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getMessagesIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(messagesIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < messagesIds_.size(); i++) {
      output.writeInt64NoTag(messagesIds_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < messagesIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(messagesIds_.getLong(i));
      }
      size += dataSize;
      if (!getMessagesIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      messagesIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.micro.access.pojo.request.signal.AckRequest)) {
      return super.equals(obj);
    }
    im.micro.access.pojo.request.signal.AckRequest other = (im.micro.access.pojo.request.signal.AckRequest) obj;

    if (!getMessagesIdsList()
        .equals(other.getMessagesIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessagesIdsCount() > 0) {
      hash = (37 * hash) + MESSAGES_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.signal.AckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.micro.access.pojo.request.signal.AckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.AckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.AckRequest)
      im.micro.access.pojo.request.signal.AckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.micro.access.pojo.request.signal.AckRequestOuterClass.internal_static_im_turms_proto_AckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.micro.access.pojo.request.signal.AckRequestOuterClass.internal_static_im_turms_proto_AckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.micro.access.pojo.request.signal.AckRequest.class, im.micro.access.pojo.request.signal.AckRequest.Builder.class);
    }

    // Construct using im.micro.access.pojo.request.signal.AckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messagesIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.micro.access.pojo.request.signal.AckRequestOuterClass.internal_static_im_turms_proto_AckRequest_descriptor;
    }

    @java.lang.Override
    public im.micro.access.pojo.request.signal.AckRequest getDefaultInstanceForType() {
      return im.micro.access.pojo.request.signal.AckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.micro.access.pojo.request.signal.AckRequest build() {
      im.micro.access.pojo.request.signal.AckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.micro.access.pojo.request.signal.AckRequest buildPartial() {
      im.micro.access.pojo.request.signal.AckRequest result = new im.micro.access.pojo.request.signal.AckRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        messagesIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.messagesIds_ = messagesIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.micro.access.pojo.request.signal.AckRequest) {
        return mergeFrom((im.micro.access.pojo.request.signal.AckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.micro.access.pojo.request.signal.AckRequest other) {
      if (other == im.micro.access.pojo.request.signal.AckRequest.getDefaultInstance()) return this;
      if (!other.messagesIds_.isEmpty()) {
        if (messagesIds_.isEmpty()) {
          messagesIds_ = other.messagesIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMessagesIdsIsMutable();
          messagesIds_.addAll(other.messagesIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.micro.access.pojo.request.signal.AckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.micro.access.pojo.request.signal.AckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList messagesIds_ = emptyLongList();
    private void ensureMessagesIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messagesIds_ = mutableCopy(messagesIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @return A list containing the messagesIds.
     */
    public java.util.List<java.lang.Long>
        getMessagesIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(messagesIds_) : messagesIds_;
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @return The count of messagesIds.
     */
    public int getMessagesIdsCount() {
      return messagesIds_.size();
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The messagesIds at the given index.
     */
    public long getMessagesIds(int index) {
      return messagesIds_.getLong(index);
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The messagesIds to set.
     * @return This builder for chaining.
     */
    public Builder setMessagesIds(
        int index, long value) {
      ensureMessagesIdsIsMutable();
      messagesIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @param value The messagesIds to add.
     * @return This builder for chaining.
     */
    public Builder addMessagesIds(long value) {
      ensureMessagesIdsIsMutable();
      messagesIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @param values The messagesIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllMessagesIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMessagesIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, messagesIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 messages_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessagesIds() {
      messagesIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.AckRequest)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.AckRequest)
  private static final im.micro.access.pojo.request.signal.AckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.micro.access.pojo.request.signal.AckRequest();
  }

  public static im.micro.access.pojo.request.signal.AckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AckRequest>
      PARSER = new com.google.protobuf.AbstractParser<AckRequest>() {
    @java.lang.Override
    public AckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.micro.access.pojo.request.signal.AckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

