// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/query_pending_messages_with_total_request.proto

package im.micro.access.pojo.request.message;

public interface QueryPendingMessagesWithTotalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.QueryPendingMessagesWithTotalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return The size.
   */
  com.google.protobuf.Int32Value getSize();
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder();
}
