// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/query_pending_messages_with_total_request.proto

package im.micro.access.pojo.request.message;

/**
 * Protobuf type {@code im.micro.proto.QueryPendingMessagesWithTotalRequest}
 */
public  final class QueryPendingMessagesWithTotalRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.micro.proto.QueryPendingMessagesWithTotalRequest)
    QueryPendingMessagesWithTotalRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryPendingMessagesWithTotalRequest.newBuilder() to construct.
  private QueryPendingMessagesWithTotalRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryPendingMessagesWithTotalRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryPendingMessagesWithTotalRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryPendingMessagesWithTotalRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (size_ != null) {
              subBuilder = size_.toBuilder();
            }
            size_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(size_);
              size_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.internal_static_im_micro_proto_QueryPendingMessagesWithTotalRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.internal_static_im_micro_proto_QueryPendingMessagesWithTotalRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.class, im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.Builder.class);
  }

  public static final int SIZE_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value size_;
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return Whether the size field is set.
   */
  public boolean hasSize() {
    return size_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return The size.
   */
  public com.google.protobuf.Int32Value getSize() {
    return size_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : size_;
  }
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder() {
    return getSize();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (size_ != null) {
      output.writeMessage(1, getSize());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (size_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSize());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest)) {
      return super.equals(obj);
    }
    im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest other = (im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest) obj;

    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (!getSize()
          .equals(other.getSize())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.micro.proto.QueryPendingMessagesWithTotalRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.micro.proto.QueryPendingMessagesWithTotalRequest)
      im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.internal_static_im_micro_proto_QueryPendingMessagesWithTotalRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.internal_static_im_micro_proto_QueryPendingMessagesWithTotalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.class, im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.Builder.class);
    }

    // Construct using im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sizeBuilder_ == null) {
        size_ = null;
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequestOuterClass.internal_static_im_micro_proto_QueryPendingMessagesWithTotalRequest_descriptor;
    }

    @java.lang.Override
    public im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest getDefaultInstanceForType() {
      return im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest build() {
      im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest buildPartial() {
      im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest result = new im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest(this);
      if (sizeBuilder_ == null) {
        result.size_ = size_;
      } else {
        result.size_ = sizeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest) {
        return mergeFrom((im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest other) {
      if (other == im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest.getDefaultInstance()) return this;
      if (other.hasSize()) {
        mergeSize(other.getSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value size_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> sizeBuilder_;
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     * @return Whether the size field is set.
     */
    public boolean hasSize() {
      return sizeBuilder_ != null || size_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     * @return The size.
     */
    public com.google.protobuf.Int32Value getSize() {
      if (sizeBuilder_ == null) {
        return size_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : size_;
      } else {
        return sizeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder setSize(com.google.protobuf.Int32Value value) {
      if (sizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        size_ = value;
        onChanged();
      } else {
        sizeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder setSize(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (sizeBuilder_ == null) {
        size_ = builderForValue.build();
        onChanged();
      } else {
        sizeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder mergeSize(com.google.protobuf.Int32Value value) {
      if (sizeBuilder_ == null) {
        if (size_ != null) {
          size_ =
            com.google.protobuf.Int32Value.newBuilder(size_).mergeFrom(value).buildPartial();
        } else {
          size_ = value;
        }
        onChanged();
      } else {
        sizeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder clearSize() {
      if (sizeBuilder_ == null) {
        size_ = null;
        onChanged();
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getSizeBuilder() {
      
      onChanged();
      return getSizeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder() {
      if (sizeBuilder_ != null) {
        return sizeBuilder_.getMessageOrBuilder();
      } else {
        return size_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : size_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getSizeFieldBuilder() {
      if (sizeBuilder_ == null) {
        sizeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getSize(),
                getParentForChildren(),
                isClean());
        size_ = null;
      }
      return sizeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.micro.proto.QueryPendingMessagesWithTotalRequest)
  }

  // @@protoc_insertion_point(class_scope:im.micro.proto.QueryPendingMessagesWithTotalRequest)
  private static final im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest();
  }

  public static im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryPendingMessagesWithTotalRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueryPendingMessagesWithTotalRequest>() {
    @java.lang.Override
    public QueryPendingMessagesWithTotalRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryPendingMessagesWithTotalRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryPendingMessagesWithTotalRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryPendingMessagesWithTotalRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.micro.access.pojo.request.message.QueryPendingMessagesWithTotalRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

