// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/update_typing_status_request.proto

package im.micro.access.pojo.request.message;

public interface UpdateTypingStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UpdateTypingStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.im.turms.proto.ChatType chat_type = 1;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  int getChatTypeValue();
  /**
   * <code>.im.turms.proto.ChatType chat_type = 1;</code>
   * @return The chatType.
   */
  im.micro.access.constant.ChatType getChatType();

  /**
   * <code>int64 to_id = 2;</code>
   * @return The toId.
   */
  long getToId();
}
