// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/group/group_join_questions_with_version.proto

package im.micro.access.pojo.bo.group;

public interface GroupJoinQuestionsWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.micro.proto.GroupJoinQuestionsWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.micro.proto.GroupJoinQuestion group_join_questions = 1;</code>
   */
  java.util.List<im.micro.access.pojo.bo.group.GroupJoinQuestion> 
      getGroupJoinQuestionsList();
  /**
   * <code>repeated .im.micro.proto.GroupJoinQuestion group_join_questions = 1;</code>
   */
  im.micro.access.pojo.bo.group.GroupJoinQuestion getGroupJoinQuestions(int index);
  /**
   * <code>repeated .im.micro.proto.GroupJoinQuestion group_join_questions = 1;</code>
   */
  int getGroupJoinQuestionsCount();
  /**
   * <code>repeated .im.micro.proto.GroupJoinQuestion group_join_questions = 1;</code>
   */
  java.util.List<? extends im.micro.access.pojo.bo.group.GroupJoinQuestionOrBuilder> 
      getGroupJoinQuestionsOrBuilderList();
  /**
   * <code>repeated .im.micro.proto.GroupJoinQuestion group_join_questions = 1;</code>
   */
  im.micro.access.pojo.bo.group.GroupJoinQuestionOrBuilder getGroupJoinQuestionsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
